import type { UiLang } from "@/lib/lang";

const artisanEn = {
  title: "Your work",
  craft: "Craft",
  bangles: "Bangle makers",
  pottery: "Pottery (making in process)",
  textile: "Textile (making in process)",
  locked: "This craft is not open yet. Choose bangle makers.",
  addStock: "Add stock",
  addHint: "Colour, how many, quality. Then post. Buyer sees it.",
  speak: "Speak",
  listening: "Listening…",
  micHint: "Say red or blue, a number, and A or B if you want.",
  micNeedChrome: "Type or tap — mic needs Chrome on http://localhost or HTTPS.",
  micDenied: "Mic blocked. Allow microphone, then tap Speak again.",
  heardPrefix: "Heard:",
  hearFail: "Could not hear. Type or tap.",
  colour: "Colour",
  red: "Red",
  blue: "Blue",
  howMany: "How many pieces",
  quality: "Quality",
  gradeA: "A · fine",
  gradeB: "B · regular",
  postStock: "Post stock",
  savedPrefix: "Saved:",
  buyerCanSee: "Buyer can see it.",
  buyerWants: "Buyer wants",
  yourStock: "Your stock",
  noneYet: "None yet.",
  size: "Size",
  wrongRole: "Log in as an artisan to use this page.",
  reliability: "Reliability",
  chat: "Chat",
  map: "Map",
  openChat: "Open chat",
};

const artisanHi: typeof artisanEn = {
  title: "आपका काम",
  craft: "काम",
  bangles: "चूड़ी बनाने वाले",
  pottery: "मिट्टी के बर्तन (अभी बन रहा है)",
  textile: "कपड़ा (अभी बन रहा है)",
  locked: "यह काम अभी खुला नहीं है। चूड़ी बनाने वाले चुनें।",
  addStock: "स्टॉक डालें",
  addHint: "रंग, कितने, गुणवत्ता। फिर भेजें। खरीदार देखेगा।",
  speak: "बोलें",
  listening: "सुन रहे हैं…",
  micHint: "लाल या नीली, एक संख्या, और चाहें तो A या B बोलें।",
  micNeedChrome: "लिखें या बटन दबाएँ — माइक के लिए Chrome + localhost/HTTPS चाहिए।",
  micDenied: "माइक बंद है। अनुमति दें, फिर फिर से बोलें दबाएँ।",
  heardPrefix: "सुना:",
  hearFail: "सुन नहीं सके। लिखें या बटन दबाएँ।",
  colour: "रंग",
  red: "लाल",
  blue: "नीली",
  howMany: "कितने टुकड़े",
  quality: "गुणवत्ता",
  gradeA: "A · बढ़िया",
  gradeB: "B · आम",
  postStock: "स्टॉक भेजें",
  savedPrefix: "सेव हो गया:",
  buyerCanSee: "खरीदार देख सकता है।",
  buyerWants: "खरीदार चाहता है",
  yourStock: "आपका स्टॉक",
  noneYet: "अभी कुछ नहीं।",
  size: "साइज़",
  wrongRole: "इस पेज के लिए कारीगर के रूप में लॉगिन करें।",
  reliability: "विश्वसनीयता",
  chat: "बात",
  map: "नक्शा",
  openChat: "बात खोलें",
};

const buyerEn = {
  title: "Buyer",
  raiseDemand: "Raise a demand",
  raiseHint: "Colour, how many, quality.",
  colour: "Colour",
  red: "Red",
  blue: "Blue",
  quantity: "Quantity",
  size: "Size",
  quality: "Quality",
  gradeA: "A · fine",
  gradeB: "B · regular",
  postDemand: "Post demand",
  postedNote: "Demand posted. Artisans see it. Matching piles are nearest first.",
  openDemands: "Open demands",
  demoOrder: "Demo order",
  cancel: "Cancel",
  tapToMatch: "Tap to match this demand",
  artisanStock: "Artisan stock that can join",
  stockHint: "Same spec first. Then nearest to the mandi.",
  noMatch: "No matching stock yet.",
  wontWork: "Won’t work for this demand",
  showMore: "Show more demo stock",
  hideMore: "Hide extra demo stock",
  wrongRole: "Log in as the buyer to use this page.",
  moneyPool: "Money pool",
  booking: "Booking",
  inPool: "In pool",
  released: "Released",
  returned: "Returned",
  payBooking: "Pay booking",
  confirmOrder: "Confirm",
  reliability: "Reliability",
  chat: "Chat",
  map: "Map",
  qtyLocked: "Quantity locked after you accepted the demo. Cannot shrink.",
  needDemo: "Confirm opens after you accept a demo piece.",
  cancelLocked: "Locked after demo accept",
  peopleNear: "People near you first. Spec match still comes first.",
};

const buyerHi: typeof buyerEn = {
  title: "खरीदार",
  raiseDemand: "मांग डालें",
  raiseHint: "रंग, कितने, गुणवत्ता।",
  colour: "रंग",
  red: "लाल",
  blue: "नीली",
  quantity: "कितने टुकड़े",
  size: "साइज़",
  quality: "गुणवत्ता",
  gradeA: "A · बढ़िया",
  gradeB: "B · आम",
  postDemand: "मांग भेजें",
  postedNote: "मांग भेज दी। कारीगर देखेंगे। मिलती स्टॉक पहले पास वाली।",
  openDemands: "खुली मांग",
  demoOrder: "डेमो ऑर्डर",
  cancel: "हटाएँ",
  tapToMatch: "इस मांग से मिलाएँ",
  artisanStock: "कारीगर का स्टॉक जो जुड़ सकता है",
  stockHint: "पहले वही रंग-साइज़। फिर मंडी के पास वाली।",
  noMatch: "अभी मिलता स्टॉक नहीं।",
  wontWork: "इस मांग में नहीं चलेगा",
  showMore: "और डेमो स्टॉक देखें",
  hideMore: "अतिरिक्त डेमो स्टॉक छिपाएँ",
  wrongRole: "इस पेज के लिए खरीदार के रूप में लॉगिन करें।",
  moneyPool: "पैसा पूल",
  booking: "बुकिंग",
  inPool: "पूल में",
  released: "रिहाई",
  returned: "वापस",
  payBooking: "बुकिंग भरें",
  confirmOrder: "कन्फर्म",
  reliability: "विश्वसनीयता",
  chat: "बात",
  map: "नक्शा",
  qtyLocked: "डेमो स्वीकार के बाद मात्रा लॉक। घटा नहीं सकते।",
  needDemo: "डेमो स्वीकार के बाद कन्फर्म खुलेगा।",
  cancelLocked: "डेमो स्वीकार के बाद लॉक",
  peopleNear: "पहले पास वाले। स्पेक मैच फिर भी पहले।",
};

export function artisanCopy(lang: UiLang) {
  return lang === "hi" ? artisanHi : artisanEn;
}

export function buyerCopy(lang: UiLang) {
  return lang === "hi" ? buyerHi : buyerEn;
}
